language: python

python:
    - 3.5

services:
    - sqlite3

env:
    global:
        - export DJANGO_SETTINGS_MODULE="config.settings.develop"
        - export PYTHONPATH=$HOME/builds/LopsanAMO/Despacho
        - export PIP_USE_MIRRORS=true

install:
    - pip install -r requirements.txt
    - pip install flake8
    - pip install pycodestyle
    - pip install autopep8

# before_script:
#     flake8
    # - mysql -e 'create database subscribers;' -u root

script:
    - python manage.py test
    - num_errors_before=`find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l`
    - echo $num_errors_before

    - cd "$TRAVIS_BUILD_DIR"
    - git config --global user.email "lopsan.molina@gmail.com"
    - git config --global user.name "Travis"
    - git remote rm origin
    - git remote add origin https://LopsanAMO:${GITHUB_API_KEY}@github.com/LopsanAMO/Despacho.git
    - git checkout $TRAVIS_BRANCH

    - find . -name \*.py -exec autopep8 --recursive --aggressive --aggressive --in-place {} +
    - num_errors_after=`find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l`
    - echo $num_errors_after

    - |
        if (( $num_errors_after < $num_errors_before )); then
            git commit -a -m "PEP-8 Fix"
            git config --global push.default simple # Push only to the current branch.
            # Make sure to make the output quiet, or else the API token will
            # leak!  This works because the API key can replace your password.
            git push --set-upstream origin master
            git push --quiet
        fi
    - cd "$TRAVIS_BUILD_DIR"

    - find . -name \*.py -exec pycodestyle --ignore=E402 {} + | wc -l

notifications:
    email:
        on_success: change
        on_failure: always
