# Generated by Django 2.0.3 on 2018-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='documents/',
                verbose_name='Documento'),
        ),
    ]
