# Generated by Django 2.0.3 on 2018-03-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='slug',
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                verbose_name='Slug'),
        ),
    ]
