# Generated by Django 2.0.3 on 2018-03-31 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20180319_0436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userclient',
            unique_together={('name',)},
        ),
    ]
