# Generated by Django 2.0.3 on 2018-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20180331_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='folderclient',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
